### PR TITLE
🐛 fix default date values

### LINKED ISSUE #75: Inaccuracy in log aggregation in "Time" table
Reported via QA:

VOL-DASH-007-0012 
Step: View the table (inital view) and observe for Professional pro bono work (Legal, IT, Research)  Jun18 
Actual: 0 hours
Expected: 10 hours

Change the filter and the 10 hrs in june appears.

### PR DESCRIPTION
**Pull request by astroash**
- default date values set to beginning of month
- fixes #75

### CODE REVIEW

File: dashboard-app/src/util/months.ts [hunk 1]
```diff
@@ -20,8 +20,8 @@ const Months: Months = {
 
     return to.diff(from, 'months');
   },
-  defaultFrom: () => moment().subtract(1, 'year').add(1, 'month').toDate(),
-  defaultTo: () => moment().toDate(),
+  defaultFrom: () => moment().subtract(1, 'year').add(1, 'month').startOf('month').toDate(),
+  defaultTo: () => moment().startOf('month').toDate(),
```
Comment (eliascodes) [inline dashboard-app/src/util/months.ts]: Should this not be `endOf('month')`?
