### PR TITLE
🐛 fix abbreviated month bug on firefox

### LINKED ISSUE #105: Data table dates are "invalid"
Presumably as a result of #90

Found on `twine-dashboard-qa` and `twine-dashboard-staging`. This appears not to be a problem when I try to reproduce locally, suggesting an issue with the data itself?

Screenshot 2019-05-22 at 14 42 03

### PR DESCRIPTION
**Pull request by astroash**
- create ISO string format before creating moment/date object

fixes #105

### CODE REVIEW

File: dashboard-app/src/util/dataManipulation/aggregatedToTableData.ts [hunk 1]
```diff
@@ -18,7 +18,14 @@ export const isDateString = (x: any): boolean => {
...
 
 export const abbreviateDateString = (x: string): string => {
-  return moment(new Date(x)).format(Months.format.table);
+  const [month, year] = x.split(' ');
+  const numericalMonth = Months.list.indexOf(month) + 1;
+  const doubleDigitNumericalMonth = numericalMonth > 9
+    ? `${numericalMonth}`
+    : `0${numericalMonth}`;
+  const isoDate = `${year}-${doubleDigitNumericalMonth}`;
+  console.log(isoDate);
```
Comment (eliascodes) [inline dashboard-app/src/util/dataManipulation/aggregatedToTableData.ts]: 🔥

File: dashboard-app/src/util/dataManipulation/aggregatedToTableData.ts [hunk 2]
```diff
@@ -18,7 +18,14 @@ export const isDateString = (x: any): boolean => {
 };
 
 export const abbreviateDateString = (x: string): string => {
-  return moment(new Date(x)).format(Months.format.table);
+  const [month, year] = x.split(' ');
```
Comment (eliascodes) [inline dashboard-app/src/util/dataManipulation/aggregatedToTableData.ts]: Is this all necessary because the `MMM YY` string isn't parsed by the date constructor in Firefox?

Comment (astroash) [reply dashboard-app/src/util/dataManipulation/aggregatedToTableData.ts]: At this point date is represented by `MMMM YYYY` eg January 2013. Moment only handles dates that are iso or rfc2822 format so it is passed to the date constructor instead (functionality that is going to be removed in future releases of `moment`).

This could be avoided if we use different month string formatting in the aggregation layer which we can look into as part of #101
